GET http://localhost:5000/online/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZpbmNlbnphNSIsImZpcnN0TmFtZSI6IkVsaXphYmV0aC5BYmJvdHQiLCJsYXN0TmFtZSI6IkRldmVuX0dyZWVuZmVsZGVyIiwiYXV0aCI6dHJ1ZSwicm9sZSI6MSwiZXhwIjoxNzM5MDAwNDIxfQ.qAp5kJjSOX8cLcfJYIWNouZRdfwmCfeJGEm2bPJtkxU


###
GET http://localhost:5000/employees/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZpbmNlbnphNSIsImZpcnN0TmFtZSI6IkVsaXphYmV0aC5BYmJvdHQiLCJsYXN0TmFtZSI6IkRldmVuX0dyZWVuZmVsZGVyIiwiYXV0aCI6dHJ1ZSwicm9sZSI6MSwiZXhwIjoxNzM5MDAwNDIxfQ.qAp5kJjSOX8cLcfJYIWNouZRdfwmCfeJGEm2bPJtkxU


###

POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123",
    "firstName": "admin",
    "lastName": "admin"
}

###
POST http://localhost:5000/login/employees
Content-Type: application/json

{
    "username": "Vincenza5",
    "password": "12345"
}
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "test",
    "password": "test12345"
}

###

GET http://localhost:5000/user/67880c26c08ce74707d34de4

###

GET http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMTIzIiwiZmlyc3ROYW1lIjoiYWRtaW41IiwibGFzdE5hbWUiOiJhZG1pbjUiLCJhdXRoIjp0cnVlLCJleHAiOjE3Mzc4MzMzMjV9.AEXbmipxje2mINRq9sdfrDAofyo2rfvvYVGV8UX-vKg

### 

PUT http://localhost:5000/user/update/67880c26c08ce74707d34de4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMTIzIiwiZmlyc3ROYW1lIjoiYWRtaW4iLCJsYXN0TmFtZSI6ImFkbWluIiwiYXV0aCI6dHJ1ZSwiZXhwIjoxNzM3ODMxNTMzfQ.hnESWoafsFOp13iN4vl5S6CHnYk4KREr8uZChRRugcA

{
    "username": "admin1235",
    "password": "admin1235",
    "firstName": "admin",
    "lastName": "admin"
}

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123",
    "firstName": "admin5",
    "lastName": "admin5"
}


###

POST http://localhost:5000/ai/message
Content-Type: application/json

{
    "message": "do you know code?"
}
